// VUE-X STORE-ACTIONS RELATED CONSTANTS:
// THESE ARE OUR SO-CALLED ACTIONS CONSTANTS...
export default {
  SAVE_ENTITY          : 'SAVE_ENTITY',
  FETCH_ENTITY         : 'FETCH_ENTITY',
  FETCH_ENTITIES       : 'FETCH_ENTITIES',
  DELETE_ENTITY        : 'DELETE_ENTITY',
  DEACTIVATE_ENTITY    : 'DEACTIVATE_ENTITY',
};