import RestBridge from"./RestBridge";import Collection from"./Collection";class Lieferstatus{_collection;_className="Lieferstatus";_TOTAL_RECORDS_COUNT=0;_multilingualEntitiesInitialized;_Persistence_Object_Identifier;_Flow_Aop_Proxy_targetMethodsAndGroupedAdvices;_Flow_Aop_Proxy_groupedAdviceChains;_Flow_Aop_Proxy_methodIsInAdviceMode;_lieferant;_artikelgruppe;restBridge;responseData=[];_END_POINTS_={add:'/api/1/stammdaten/lieferstatus/add',set:'/api/1/stammdaten/lieferstatus/set',list:'/api/1/stammdaten/lieferstatus/list',show:'/api/1/stammdaten/lieferstatus/show',delete:'/api/1/stammdaten/lieferstatus/delete',deactivate:'/api/1/stammdaten/lieferstatus/deactivate',};constructor(instanceData=null,config={baseURL:null,header:null,config:null,endPoint:null}){this.restBridge=new RestBridge(config);if(instanceData!==null&&typeof instanceData==="object"){this.autoSetClassProps(instanceData);}}
autoSetClassProps(data){let loopKey;for(loopKey in data){if(this.hasOwnProperty(loopKey)||loopKey in this){this[loopKey]=data[loopKey];}}}
async list(params={limit:null,orientation:null,sorting:null,offset:null}){let cueKey,qString=[];let queryString='';if(typeof params==='object'&&Object.keys(params).length>0){for(cueKey in params){const val=params[cueKey];qString.push(`${cueKey}=${val}`);}
queryString=qString.join("&");}
queryString=queryString?`?${queryString}`:queryString;let response=this.restBridge.fetchEntries(`${this._END_POINTS_.list}${queryString}`);response.then(()=>{this.responseData=this.restBridge.response.data;const collection=new Collection('Lieferstatus',this.responseData);this._collection=collection.getDataCollection();});return await response;}
async add(params={}){let endPoint=`${this._END_POINTS_.add}`;let response=this.restBridge.createEntry(endPoint,params);response.then(()=>{this.responseData=this.restBridge.response.data;});return await response;}
async update(params={uid:null}){let uid=params.uid;if(params.constructor.name==='FormData'){uid=params.get('uid');}
let endPoint=`${this._END_POINTS_.set}/${uid}`;let response=this.restBridge.updateEntry(endPoint,params);response.then(()=>{this.responseData=this.restBridge.response.data;});return await response;}
async set(params={uid:null}){return await this.update(params);}
async show(params={uid:null}){let endPoint=`${this._END_POINTS_.show}/${params.uid}`;let response=this.restBridge.fetchEntry(endPoint);response.then(()=>{this.responseData=this.restBridge.response.data;});return await response;}
async delete(params={uid:null}){let endPoint=`${this._END_POINTS_.delete}/${params.uid}`;let response=this.restBridge.deleteEntry(endPoint);response.then(()=>{this.responseData=this.restBridge.response.data;});return await response;}
async deactivate(params={uid:null}){let endPoint=`${this._END_POINTS_.deactivate}/${params.uid}`;let response=this.restBridge.deactivateEntry(endPoint);response.then(()=>{this.responseData=this.restBridge.response.data;});return await response;}
set collection(collection){this._collection=collection;}
get collection(){return this._collection;}
get className(){return this._className;}
get TOTAL_RECORDS_COUNT(){return this._TOTAL_RECORDS_COUNT;}
set TOTAL_RECORDS_COUNT(TOTAL_RECORDS_COUNT){this._TOTAL_RECORDS_COUNT=TOTAL_RECORDS_COUNT;}
get multilingualEntitiesInitialized(){return this._multilingualEntitiesInitialized;}
get Persistence_Object_Identifier(){return this._Persistence_Object_Identifier;}
get Flow_Aop_Proxy_targetMethodsAndGroupedAdvices(){return this._Flow_Aop_Proxy_targetMethodsAndGroupedAdvices;}
get Flow_Aop_Proxy_groupedAdviceChains(){return this._Flow_Aop_Proxy_groupedAdviceChains;}
get Flow_Aop_Proxy_methodIsInAdviceMode(){return this._Flow_Aop_Proxy_methodIsInAdviceMode;}
get lieferant(){return this._lieferant;}
get artikelgruppe(){return this._artikelgruppe;}
set multilingualEntitiesInitialized(multilingualEntitiesInitialized){this._multilingualEntitiesInitialized=multilingualEntitiesInitialized;}
set Persistence_Object_Identifier(Persistence_Object_Identifier){this._Persistence_Object_Identifier=Persistence_Object_Identifier;}
set Flow_Aop_Proxy_targetMethodsAndGroupedAdvices(Flow_Aop_Proxy_targetMethodsAndGroupedAdvices){this._Flow_Aop_Proxy_targetMethodsAndGroupedAdvices=Flow_Aop_Proxy_targetMethodsAndGroupedAdvices;}
set Flow_Aop_Proxy_groupedAdviceChains(Flow_Aop_Proxy_groupedAdviceChains){this._Flow_Aop_Proxy_groupedAdviceChains=Flow_Aop_Proxy_groupedAdviceChains;}
set Flow_Aop_Proxy_methodIsInAdviceMode(Flow_Aop_Proxy_methodIsInAdviceMode){this._Flow_Aop_Proxy_methodIsInAdviceMode=Flow_Aop_Proxy_methodIsInAdviceMode;}
set lieferant(lieferant){this._lieferant=lieferant;}
set artikelgruppe(artikelgruppe){this._artikelgruppe=artikelgruppe;}
fetchFormConfig(){return{"multilingualEntitiesInitialized":{"type":"toggleSwitch","fieldType":"toggleSwitch","multiLingual":false,"multiFields":false,"readOnly":false,"validation":{"strategies":["NOT_EMPTY","BOOLEAN"]},"fieldName":"multilingualEntitiesInitialized","fieldLabel":"MultilingualEntitiesInitialized","defaultLang":"de","lang":["de","fr","it","en"],"bypassed":false},"Persistence_Object_Identifier":{"type":"input","fieldType":"text","multiLingual":false,"multiFields":false,"readOnly":false,"validation":{"strategies":["NOT_EMPTY","STRING"]},"fieldName":"Persistence_Object_Identifier","fieldLabel":"Persistence_Object_Identifier","defaultLang":"de","lang":["de","fr","it","en"],"bypassed":false},"Flow_Aop_Proxy_targetMethodsAndGroupedAdvices":{"type":"text","fieldType":"text","multiLingual":false,"multiFields":false,"readOnly":false,"validation":{"strategies":["NOT_EMPTY","STRING"]},"fieldName":"Flow_Aop_Proxy_targetMethodsAndGroupedAdvices","fieldLabel":"Flow_Aop_Proxy_targetMethodsAndGroupedAdvices","defaultLang":"de","lang":["de","fr","it","en"],"bypassed":false},"Flow_Aop_Proxy_groupedAdviceChains":{"type":"text","fieldType":"text","multiLingual":false,"multiFields":false,"readOnly":false,"validation":{"strategies":["NOT_EMPTY","STRING"]},"fieldName":"Flow_Aop_Proxy_groupedAdviceChains","fieldLabel":"Flow_Aop_Proxy_groupedAdviceChains","defaultLang":"de","lang":["de","fr","it","en"],"bypassed":false},"Flow_Aop_Proxy_methodIsInAdviceMode":{"type":"text","fieldType":"text","multiLingual":false,"multiFields":false,"readOnly":false,"validation":{"strategies":["NOT_EMPTY","STRING"]},"fieldName":"Flow_Aop_Proxy_methodIsInAdviceMode","fieldLabel":"Flow_Aop_Proxy_methodIsInAdviceMode","defaultLang":"de","lang":["de","fr","it","en"],"bypassed":false},"lieferant":{"type":"select","fieldType":"select","multiLingual":false,"multiFields":false,"readOnly":false,"validation":{"strategies":["NOT_EMPTY","STRING"]},"fieldName":"lieferant","fieldLabel":"Lieferant","defaultLang":"de","lang":["de","fr","it","en"],"bypassed":false},"artikelgruppe":{"type":"select","fieldType":"select","multiLingual":false,"multiFields":false,"readOnly":false,"validation":{"strategies":["NOT_EMPTY","STRING"]},"fieldName":"artikelgruppe","fieldLabel":"Artikelgruppe","defaultLang":"de","lang":["de","fr","it","en"],"bypassed":false}};}
fetchFieldsConfig(){return{"lieferant":{"name":"lieferant","id":"lieferant","type":"Kreditor","inputType":"DropDown","class":"form-control egl-label","label":"Kreditor","inputFieldHint":"<span class='egl-hint'>The Supplier/Creditor (Lieferant/Kreditor)</span>","readOnly":false,"useLabel":true,"isManyToOne":true,"isEntity":true,"defaultLang":"de","optionsMap":{"value":"uid","label":"bezeichnung"},"optionsClass":"Kreditor","inputOptions":[],"inputRequired":true,"dataAttributes":"data-class='Lieferstatus'","showInTable":true,"showInForm":true,"validationStrategies":["STRING","NOT_EMPTY"]},"artikelgruppe":{"name":"artikelgruppe","id":"artikelgruppe","type":"Artikelgruppe","inputType":"DropDown","class":"form-control egl-artikelgruppe","label":"Artikelgruppe","inputFieldHint":"<span class='egl-hint'>The Supply-Status' Article-Group \u00abArtikelgruppe\u00bb</span>","readOnly":false,"useLabel":true,"isManyToOne":true,"isEntity":true,"defaultLang":"de","optionsMap":{"value":"uid","label":"bezeichnung"},"optionsClass":"Artikelgruppe","inputOptions":[],"inputRequired":true,"dataAttributes":"data-class='Artikel'","showInTable":true,"showInForm":true,"validationStrategies":["STRING","NOT_EMPTY"]}};}}
export default Lieferstatus;